import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

input_excel_path = "C:/Users/xiach/OneDrive/桌面/house_prices.xlsx"
df = pd.read_excel(input_excel_path)
df['date_of_sale'] = df['date_of_sale'].str.replace('Såld ', '')
df['date_of_sale'] = pd.to_datetime(df['date_of_sale'], format='%d %B %Y', errors='coerce')
df['location'] = df['location'].str.replace(r'\s+', ' ', regex=True).str.strip()
df[['boarea', 'biarea']] = df['total_area'].str.extract(r'(\d+)\+(\d+)')
df['boarea'] = pd.to_numeric(df['boarea'], errors='coerce')
df['biarea'] = pd.to_numeric(df['biarea'], errors='coerce')
df['closing_price'] = pd.to_numeric(df['closing_price'], errors='coerce')
print(df)
min_price = df['closing_price'].min()
q1 = df['closing_price'].quantile(0.25)
median = df['closing_price'].median()
q3 = df['closing_price'].quantile(0.75)
max_price = df['closing_price'].max()
print("\nFive-number summary for closing prices:")
print(f"Minimum Price: {min_price}")
print(f"1st Quartile (Q1): {q1}")
print(f"Median: {median}")
print(f"3rd Quartile (Q3): {q3}")
print(f"Maximum Price: {max_price}")

plt.figure(figsize=(10, 6))
plt.boxplot(df['closing_price'].dropna(), vert=False)
plt.title('Boxplot of Closing Prices for Houses Sold in 2022')
plt.xlabel('Price (SEK)')
plt.xticks(ticks=np.arange(0, 2.5e7, 5e6), labels=[f'{x/1e6:.1f}M SEK' for x in np.arange(0, 2.5e7, 5e6)])
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()
plt.figure(figsize=(10, 6))
plt.hist(df['closing_price'].dropna(), bins=20, edgecolor='black', alpha=0.7)
plt.title('Histogram of Closing Prices for Houses Sold in 2022')
plt.xlabel('Price (SEK)')
plt.ylabel('Frequency')
plt.xticks(ticks=np.arange(0, 2.5e7, 5e6), labels=[f'{x/1e6:.1f}M SEK' for x in np.arange(0, 2.5e7, 5e6)])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
plt.figure(figsize=(10, 6))
plt.scatter(df['boarea'], df['closing_price'], alpha=0.7, edgecolor='k')
plt.title('Scatter Plot of Closing Price vs Boarea')
plt.xlabel('Boarea (m²)')
plt.ylabel('Closing Price (SEK)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()
plt.figure(figsize=(10, 6))
scatter = plt.scatter(df['boarea'], df['closing_price'], c=df['rooms'], cmap='viridis', alpha=0.7, edgecolor='k')
plt.title('Scatter Plot of Closing Price vs Boarea (Colored by Number of Rooms)')
plt.xlabel('Boarea (m²)')
plt.ylabel('Closing Price (SEK)')
plt.colorbar(scatter, label='Number of Rooms')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()
